### PR TITLE
Module added to demonstrate Pocketsphinx offline speech recognition as standalone app on devices running Android Wear 2.0

### PR DESCRIPTION
**Pull request by mahula**
Hello,

I extended pocketsphinx-android-demo by a module for wearables, which aims to demonstrate the Pocketsphinx offline speech recognition as a standalone app on devices running Android Wear 2.0.

The changes include

- the creation of a library module, which now contains all the code and data both Android apps share

- adaption of the existing app module regarding the shared code

- creation of module for standalone Android Wear app

### CODE REVIEW

**Comment by nshmyrev** [comment]
Thank you for your contribution. Unfortunately I don't think we need to complicate demo that much by code sharing. Don't you think we could have a separate pocketsphinx-android-mobile-demo instead? I also think that adaptation of the original demo for mobile is not that hard, in the end is just a different layout of labels, nothing more.

**Comment by mahula** [comment]
Of course there can be a seperate pocketsphinx-android-wear-demo to keep the original pocketsphinx-android-demo code as it is.

Yes, obviously the adaptation of the original demo is no rocket schience. The purpose is just to support Pocketsphinx by making the existing Android demo runnable as a standalone app on Android Wear 2.0, so that when the Wear 2.0 devices are available, Pocketsphinx can also be demoed on those.

**Comment by mahula** [comment]
Would you accept a seperate pocketsphinx-android-wear-demo?

**Comment by nshmyrev** [comment]
Yes, I think its more reasonable. Maybe we can just have two top-level folders inside android-demo - one is for mobile, another is for wear, what do you think? We also need an example for speech service, I could probably make it a third folder.

**Comment by mahula** [comment]
Yes, that makes sense.

**Comment by mahula** [comment]
Just to avoid misunderstanding:
Do you mean keeping the one single repository "pocketsphinx-android-demo
" and changing it by moving its contemporary contents into a subfolder "mobile" and adding a second subfolder "wear" for the wear version of it and andding a third subfolder e.g. "speech-service" for the speech service code?

From an Adroid perspective, it would be common to have one project (e.g. "pocketsphinx-android-demo") containing two modules (e.g. "mobile" and "wear"), which can be tested, debugged, buld and run seperately. The two modules would not share as much code as in the version I implemented. They would only share the existing library "pocketsphinx-android-5prealpha-nolib.jar" from the original demo.
Browsing the code, and working on it in Android Studio would be more straight forward this way, instead of having to handle two seperate Android projects. But the modules for the different device classes would still be seperated clearly.
What do you think?

**Comment by mahula** [comment]
Yes, you cann easily start different subprojects/modules from Android Studio.
What about the speech service, will it also build upon Pocketsphinx?

**Comment by nshmyrev** [comment]
Yes, the idea with the service is to run continuously and activate application even if app is in background.

**Comment by mahula** [comment]
That sounds pretty interesting.

**Comment by mahula** [comment]
Okay, so at first I will change my fork to contain the original demo app and the module for wearables in separate suubfolders, not sharing any code or data so far.

(If that will be accepted, then later on I would suggest to let them both just share the pre-compiled library "pocketsphinx-android-5prealpha-nolib.jar", because both modules build upon it. That will later on ensure, that any changes on this Pocketsphinx library will simultaniously be applied and available for both modules.)

**Comment by nshmyrev** [comment]
Great, thanks

**Comment by mahula** [comment]
Now the fork contains two separate modules (in subfolders "app" and "wear"), not sharing any code or data.

**Comment by nshmyrev** [comment]
Thanks, but I see now assets are simply deleted? Could you add them back please?

**Comment by mahula** [comment]
The assets are added back now.

**Comment by ozbek** [comment]
IMHO, this PR adds lots of unnecessary code (and assets and resource) duplication.

**Comment by mahula** [comment]
In deed.
The first version, as you can read in the first comment of the PR, had no duplications.
The code and data needed for both versions, the Android phone/tablet app and the Android Wear app, was held in a library module to be shared amongst the other modules.
Having the three modules was said to complicate the demo's code.
So it has been decided to just have the two modules for different device classes not sharing any code or data to keep the code of the original demo as it was.
The current code is the compromise. It shows, that the demo also runs on Android Wear.
As stated above the next step could be to have the two modules share the Pocketsphnx library, the JNI libraries and the assets.

**Comment by nshmyrev** [comment]
I think what I will do - include jni into jar, put jar and major assets in library project. Hopefully it will be better then.

**Comment by mahula** [comment]
But what about the initial version of the code in this pull request?
It did not have code or data duplication and did not really complicate the demo code.

**Comment by mahula** [comment]
So, which version would be acceptable?
The current version with code duplicates, but the suggested library project containing the jni and assets
or the initial version of the pull request without code duplicates, without jni and asset duplicates and the library project containing jni and assets?

**Comment by nshmyrev** [comment]
Should be fixed now, please check. Thank you for the pull request.

**Pull request closed without merging**
